# Generated by Django 4.1.1 on 2022-09-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_index', '0004_alter_log_created_by_findindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findindex',
            name='json',
            field=models.JSONField(),
        ),
    ]
