# Generated by Django 4.1.1 on 2022-09-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_index', '0005_alter_findindex_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='findindex',
            old_name='json',
            new_name='log_data',
        ),
    ]
